##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  fedora:
    # Useful URL: https://src.fedoraproject.org/cgit/rpms/mate-wayland-session.git
    - autoconf-archive
    - gcc
    - desktop-file-utils
    - git
    - make
    - mate-common
    - meson
    - redhat-rpm-config

  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    - autopoint
    - gcc
    - git
    - libxml2-dev
    - make
    - mate-common
    - meson
    - yelp-tools

variables:

before_scripts:

build_scripts:

  - ./autogen.sh
  - make -j

after_scripts:

  - make distcheck

releases:
  draft: false
  prerelease: false
  checksum: true
  file_glob: true
  files: mate-wayland-session-*.tar.xz
  github_release:
    tags: true
    overwrite: true
    base_version: 1.28.0
    notify_servers:
      - https://release.mate-desktop.org/release
