##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  fedora:
    # Useful URL: https://src.fedoraproject.org/cgit/rpms/mate-wayland-session.git
    - autoconf-archive
    - gcc
    - desktop-file-utils
    - git
    - make
    - mate-common
    - meson
    - redhat-rpm-config

  ubuntu:
    - autoconf-archive
    - autopoint
    - clang
    - clang-tools
    - gcc
    - git
    - make
    - mate-common
    - meson

variables:

before_scripts:

build_scripts:

  - NOCONFIGURE=1 ./autogen.sh

after_scripts:

  - make distcheck

releases:
  draft: false
  prerelease: false
  checksum: true
  file_glob: true
  files: mate-wayland-session-*.tar.xz
  github_release:
    tags: true
    overwrite: true
    base_version: 1.28.0
    notify_servers:
      - https://release.mate-desktop.org/release
